language: node_js

node_js:
  - "node"

sudo: false

os:
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install

script:
  - npm test --silent
  - npm run lint

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - npm i -g vsce

deploy:
  - provider: script
    skip_cleanup: true
    script: vsce -p ${VSCODE_KEY}
    on:
      branch: master
