dist: xenial
services:
  - xvfb

language: node_js

node_js:
  - "node"

sudo: false

install:
  - npm install

script:
  - npm test
  - npm run lint
  - npm i -g vsce

deploy:
  - provider: script
    skip_cleanup: true
    script: vsce publish -p ${VSCODE_KEY}
    on:
      branch: master
      tags: true

after_script:
  - bash <(curl -s https://codecov.io/bash)
